#!/usr/bin/python3
import sys

def factorize(n):
    if n % 2 == 0:
        return n // 2, 2
    for i in range(3, n // 2 + 1, 2):
        if n % i == 0:
            return n // i, i

def factorization():
    try:
        files = sys.argv[1]
        with open(files) as f:
            for numbs in f:
                numbs = int(numbs)
                p, q = factorize(numbs)
                print("{}={}*{}".format(numbs, p, q))
    except (IndexError, FileNotFoundError, ValueError):
        pass

if __name__ == "__main__":
    factorization()
